"""Trusted mechanical verification registry.

Verifier specifications are supplied by trusted application configuration,
not generated by the model. Every required mechanical acceptance criterion
must have a registered verifier; missing or failing verification fails closed.
"""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, Mapping, Optional

from . import sandbox
from .permission_broker import derive_policy

PASSED = "passed"
FAILED = "failed"
UNKNOWN = "unknown"
VALID_STATUSES = {PASSED, FAILED, UNKNOWN}


@dataclass(frozen=True)
class VerificationResult:
    status: str
    evidence: dict

    def __post_init__(self):
        if self.status not in VALID_STATUSES:
            raise ValueError(f"invalid verification status: {self.status}")


Verifier = Callable[[dict, dict, str, dict], VerificationResult]


class VerifierRegistry:
    def __init__(self):
        self._verifiers: Dict[str, Verifier] = {}

    def register(self, name: str, verifier: Verifier) -> None:
        if not name or name in self._verifiers:
            raise ValueError(f"verifier already registered or invalid: {name}")
        self._verifiers[name] = verifier

    def run(
        self, name: str, intent: dict, workflow: dict,
        workspace_dir: str, config: dict,
    ) -> VerificationResult:
        verifier = self._verifiers.get(name)
        if verifier is None:
            return VerificationResult(UNKNOWN, {"reason": "unknown_verifier", "name": name})
        try:
            return verifier(intent, workflow, workspace_dir, config)
        except Exception as exc:
            return VerificationResult(
                UNKNOWN, {"reason": "verifier_exception", "type": type(exc).__name__, "message": str(exc)}
            )


def _json_equals(_intent: dict, _workflow: dict, workspace_dir: str, config: dict) -> VerificationResult:
    relative = Path(config["path"])
    if relative.is_absolute() or ".." in relative.parts:
        return VerificationResult(FAILED, {"reason": "unsafe_path", "path": str(relative)})
    path = Path(workspace_dir) / relative
    try:
        actual = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        return VerificationResult(FAILED, {"reason": "json_read_failed", "message": str(exc)})
    expected = config.get("expected")
    return VerificationResult(
        PASSED if actual == expected else FAILED,
        {"path": str(relative), "expected": expected, "actual": actual},
    )


def _exact_files(_intent: dict, _workflow: dict, workspace_dir: str, config: dict) -> VerificationResult:
    actual = sorted(
        str(path.relative_to(workspace_dir))
        for path in Path(workspace_dir).rglob("*") if path.is_file()
    )
    expected = sorted(config.get("paths", []))
    return VerificationResult(
        PASSED if actual == expected else FAILED,
        {"expected": expected, "actual": actual},
    )


def _python_unittest(intent: dict, _workflow: dict, workspace_dir: str, config: dict) -> VerificationResult:
    test_path = Path(config["path"])
    if test_path.is_absolute() or ".." in test_path.parts:
        return VerificationResult(FAILED, {"reason": "unsafe_path", "path": str(test_path)})
    policy = derive_policy(intent, workspace_dir)
    result = sandbox.run_verifier(
        ["python", "-m", "unittest", "-q", str(test_path)],
        policy, workspace_dir, timeout=int(config.get("timeout", 60)),
    )
    return VerificationResult(
        PASSED if result["exit_code"] == 0 else FAILED,
        {"path": str(test_path), **result},
    )


DEFAULT_REGISTRY = VerifierRegistry()
DEFAULT_REGISTRY.register("json_equals", _json_equals)
DEFAULT_REGISTRY.register("exact_files", _exact_files)
DEFAULT_REGISTRY.register("python_unittest", _python_unittest)


def _structural_evidence(workflow: dict) -> dict:
    unexpected = {}
    nonterminal = {}
    for step in workflow.get("steps", []):
        if step.get("status") not in ("completed", "skipped"):
            nonterminal[step.get("id")] = step.get("status")
        diff = step.get("_workspace_diff", {})
        touched = set(diff.get("added", {})) | set(diff.get("modified", {})) | set(diff.get("removed", {}))
        extra = sorted(touched - set(step.get("expected_outputs", [])))
        if extra:
            unexpected[step.get("id")] = extra
    return {"nonterminal_steps": nonterminal, "unexpected_outputs": unexpected}


def run_mechanical_verifiers(
    intent: dict, workflow: dict, workspace_dir: str,
    verifier_specs: Mapping[str, dict],
    registry: Optional[VerifierRegistry] = None,
) -> dict:
    """Run trusted per-criterion verifiers and fail closed structurally."""
    registry = registry or DEFAULT_REGISTRY
    structural = _structural_evidence(workflow)
    structural_failed = bool(structural["nonterminal_steps"] or structural["unexpected_outputs"])
    results = {}
    evidence = {}

    for criterion in intent.get("acceptance_criteria", []):
        if not criterion.get("required") or criterion.get("automation") != "mechanical":
            continue
        criterion_id = criterion["id"]
        spec = verifier_specs.get(criterion_id)
        if not spec:
            result = VerificationResult(UNKNOWN, {"reason": "missing_verifier_spec"})
        else:
            result = registry.run(
                spec.get("type", ""), intent, workflow, workspace_dir,
                spec.get("config", {}),
            )
        status = FAILED if structural_failed and result.status == PASSED else result.status
        results[criterion_id] = status
        evidence[criterion_id] = result.evidence

    return {
        "results": results,
        "evidence": evidence,
        "structural": structural,
    }
